"""Add blocked status to users

Revision ID: 87ea2219f2f5
Revises: 9e901268d0f6
Create Date: 2025-10-14 11:18:09.411280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87ea2219f2f5'
down_revision = '9e901268d0f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('driver', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_blocked', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('blocked_reason', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('blocked_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_driver_is_blocked'), ['is_blocked'], unique=False)

    with op.batch_alter_table('passenger', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_blocked', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('blocked_reason', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('blocked_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_passenger_is_blocked'), ['is_blocked'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('passenger', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_passenger_is_blocked'))
        batch_op.drop_column('blocked_at')
        batch_op.drop_column('blocked_reason')
        batch_op.drop_column('is_blocked')

    with op.batch_alter_table('driver', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_driver_is_blocked'))
        batch_op.drop_column('blocked_at')
        batch_op.drop_column('blocked_reason')
        batch_op.drop_column('is_blocked')

    # ### end Alembic commands ###
