"""Initial migration

Revision ID: 9e901268d0f6
Revises: 
Create Date: 2025-10-11 14:09:35.448060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e901268d0f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('profile_picture', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('driver',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_uid', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('vehicle_type', sa.String(length=50), nullable=False),
    sa.Column('vehicle_details', sa.String(length=150), nullable=False),
    sa.Column('vehicle_plate_number', sa.String(length=50), nullable=True),
    sa.Column('license_info', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('profile_picture', sa.String(length=255), nullable=True),
    sa.Column('license_document', sa.String(length=255), nullable=True),
    sa.Column('vehicle_document', sa.String(length=255), nullable=True),
    sa.Column('join_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('current_lat', sa.Float(), nullable=True),
    sa.Column('current_lon', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('driver_uid')
    )
    op.create_table('passenger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('passenger_uid', sa.String(length=20), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('profile_picture', sa.String(length=255), nullable=True),
    sa.Column('join_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('passenger_uid'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('ride',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('passenger_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('pickup_address', sa.String(length=255), nullable=True),
    sa.Column('pickup_lat', sa.Float(), nullable=False),
    sa.Column('pickup_lon', sa.Float(), nullable=False),
    sa.Column('dest_address', sa.String(length=255), nullable=False),
    sa.Column('dest_lat', sa.Float(), nullable=True),
    sa.Column('dest_lon', sa.Float(), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=False),
    sa.Column('fare', sa.Float(), nullable=False),
    sa.Column('vehicle_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('request_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('assigned_time', sa.DateTime(), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('payment_method', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['driver.id'], ),
    sa.ForeignKeyConstraint(['passenger_id'], ['passenger.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ride_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.Column('feedback_type', sa.String(length=50), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['ride_id'], ['ride.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ride_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback')
    op.drop_table('ride')
    op.drop_table('setting')
    op.drop_table('passenger')
    op.drop_table('driver')
    op.drop_table('admin')
    # ### end Alembic commands ###
